sudo: required
services:
  - docker

before_install:
  - docker build -t brentonamorris/docker-react -f Dockerfile.dev .

script:
  - docker run brentonamorris/docker-react npm run test -- --coverage
